name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile code
        run: javac -d out $(find src -name "*.java")

      - name: Run tests
        run: |
          mkdir -p test-results
          javac -cp ".:lib/junit-5.9.1.jar" -d out $(find test -name "*.java")
          java -jar lib/junit-platform-console-standalone-1.9.1.jar -cp out --scan-classpath
